[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://brasserie-bot-api.onrender.com"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Fix EACCES warnings
  NPM_FLAGS = "--no-optional"

# Redirects voor client-side routing - alleen nodig in productie, niet in development
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Netlify Functions configuratie (serverless)
[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]
  node_bundler = "esbuild"

# Cache headers voor betere performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"