[build]
  # Publish the frontend/public directory directly
  publish = "frontend/public"
  # Process HTML files to inject environment variables
  command = "node build-scripts/process-html.js"

# Configuratie voor Netlify plaatshoudervervanging
[context.production]
  [context.production.environment]
    NODE_VERSION = "18"
    SUPABASE_DATABASE_URL = "https://yucpwawshjmonwsgvsfq.supabase.co"
    SUPABASE_ANON_KEY = "from_netlify_ui"
    ENABLE_ERROR_MONITORING = "true"
    ENABLE_CACHING = "true"

[context.deploy-preview]
  [context.deploy-preview.environment]
    SUPABASE_DATABASE_URL = "https://yucpwawshjmonwsgvsfq.supabase.co"
    SUPABASE_ANON_KEY = "from_netlify_ui"

[context.branch-deploy]
  [context.branch-deploy.environment]
    SUPABASE_DATABASE_URL = "https://yucpwawshjmonwsgvsfq.supabase.co"
    SUPABASE_ANON_KEY = "from_netlify_ui"

# Redirects for direct access to dashboard
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302
  force = true

# Redirect van oudere dashboard naar nieuwe dashboard pagina
[[redirects]]
  from = "/dashboard-fixed.html"
  to = "/dashboard.html"
  status = 301
  force = true

# Cache headers for better performance
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"