[build]
  # Publish the frontend/public directory directly
  publish = "frontend/public"
  # No build command needed for static files
  command = "echo 'No build command needed for static files'"

# Redirects for direct access to dashboard
[[redirects]]
  from = "/"
  to = "/dashboard-fixed.html"
  status = 302
  force = true

# Cache headers for better performance
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"