# BrasserieBot Netlify configuratie - Root

[build]
  # De static HTML site bevindt zich in frontend/public
  publish = "frontend/public"
  # Geen build command nodig, GitHub Actions handelt het process-html script
  command = "echo 'No build command needed - HTML processing done in GitHub Actions'"

[build.environment]
  NODE_VERSION = "18"
  # Supabase variabelen worden tijdens deploy ingevuld door GitHub Actions

# Deze redirect is nodig om client-side routing te ondersteunen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Dit betekent "als het bestand niet bestaat, val terug op index.html"
  force = false

# Configuratie voor de Netlify CLI en Dev server
[dev]
  publish = "frontend/public"
  port = 8888
  autoLaunch = true
  
# Variabele substitutie (wordt tijdens de CI/CD pipeline ingevuld)
[context.production.environment]
  SUPABASE_DATABASE_URL = ""
  SUPABASE_ANON_KEY = ""