services:
  - type: web
    name: brasserie-bot-api
    env: node
    region: frankfurt
    plan: standard
    buildCommand: npm ci && npx prisma generate
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: brasserie-bot-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: AUTODEV_ENABLED
        value: "true"
      - key: AUTODEV_SERVICE_URL
        value: "https://brasserie-bot-autodev.onrender.com"

  - type: web
    name: brasserie-bot-autodev
    env: node
    region: frankfurt
    plan: standard
    buildCommand: npm ci
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DASHBOARD_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: brasserie-bot-db
          property: connectionString
      - key: CLAUDE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: "gcp-starter"
      - key: PINECONE_INDEX
        value: "brasserie-bot-knowledge"
      - key: KNOWLEDGE_BASE_PATH
        value: "/app/knowledge"
      - key: LOG_LEVEL
        value: "info"

  - type: web
    name: brasserie-bot-autodev-dashboard
    env: node
    region: frankfurt
    plan: standard
    buildCommand: npm ci
    startCommand: npm run dashboard:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: AUTODEV_SERVICE_URL
        value: "https://brasserie-bot-autodev.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: brasserie-bot-db
          property: connectionString
      - key: LOG_LEVEL
        value: "info"

databases:
  - name: brasserie-bot-db
    region: frankfurt
    plan: standard