# BrasserieBot GCP Infrastructure - Backend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: brasserie-bot-backend
  namespace: brasserie-bot
  labels:
    app: brasserie-bot
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: brasserie-bot
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: brasserie-bot
        component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: brasserie-bot-app
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/brasserie-bot-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-credentials
              key: claude-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-credentials
              key: pinecone-api-key
        - name: PUBSUB_PROJECT_ID
          value: "PROJECT_ID"
        - name: STORAGE_BUCKET
          value: "brasserie-bot-assets-prod-assets"
        - name: AUTODEV_ENABLED
          value: "true"
        - name: AUTODEV_SERVICE_URL
          value: "http://brasserie-bot-autodev.brasserie-bot-autodev.svc.cluster.local:3001"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
      - name: tmp-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - brasserie-bot
                - key: component
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: brasserie-bot
            component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: brasserie-bot-backend
  namespace: brasserie-bot
  labels:
    app: brasserie-bot
    component: backend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "brasserie-bot-backend-config"}'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: brasserie-bot
    component: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brasserie-bot-backend
  namespace: brasserie-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brasserie-bot-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: brasserie-bot-backend-config
  namespace: brasserie-bot
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 80
  securityPolicy:
    name: "brasserie-bot-security-policy"
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60